arm_robot:      
  arm1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm1_joint
    pid: {p: 100.0, i: 0.1, d: 80.0, i_clamp_min: -0.0, i_clamp_max: 0.0}

  arm2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm2_joint
    pid: {p: 100.0, i: 0.1, d: 80.0, i_clamp_min: -0.0, i_clamp_max: 0.0}

  arm3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm3_joint
    pid: {p: 100.0, i: 0.1, d: 80.0, i_clamp_min: -0.0, i_clamp_max: 0.0}

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10 