arm_Gen3_robot:      
  body2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: body2_joint
    pid: {p: 100.0, i: 0.1, d: 80.0, i_clamp_min: -0.0, i_clamp_max: 0.0}

  body3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: body3_joint
    pid: {p: 100.0, i: 0.1, d: 80.0, i_clamp_min: -0.0, i_clamp_max: 0.0}

  body4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: body4_joint
    pid: {p: 100.0, i: 0.1, d: 80.0, i_clamp_min: -0.0, i_clamp_max: 0.0}

  body5_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: body5_joint
    pid: {p: 100.0, i: 0.1, d: 80.0, i_clamp_min: -0.0, i_clamp_max: 0.0}

  body6_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: body6_joint
    pid: {p: 100.0, i: 0.1, d: 80.0, i_clamp_min: -0.0, i_clamp_max: 0.0}

  body7_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: body7_joint
    pid: {p: 100.0, i: 0.1, d: 80.0, i_clamp_min: -0.0, i_clamp_max: 0.0}

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10 